
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Mutator functions for setting with no sanity checking.  Use these to
 *  set structure members from functions outside the alt_str_t
 *  class.  These macros perform no data validation.  Hence, they achieve
 *  maximum performance where data are guaranteed correct by other means.
 *  Use the mutator functions (same name as the macro, but lower case)
 *  for more robust code with a small performance penalty.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

/* temp-alt-str-mutators.c */
int alt_str_set_count(alt_str_t *alt_str_ptr, size_t new_count);
int alt_str_set_strings(alt_str_t *alt_str_ptr, char **new_strings);
int alt_str_set_strings_ae(alt_str_t *alt_str_ptr, size_t c, char *new_strings_element);
int alt_str_set_strings_cpy(alt_str_t *alt_str_ptr, char **new_strings, size_t array_size);
