    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the alt_str_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define ALT_STR_COUNT(ptr)              ((ptr)->count)
#define ALT_STR_STRINGS(ptr)            ((ptr)->strings)
#define ALT_STR_STRINGS_AE(ptr,c)       ((ptr)->strings[c])
