
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Mutator functions for setting with no sanity checking.  Use these to
 *  set structure members from functions outside the bl_gff3_region_t
 *  class.  These macros perform no data validation.  Hence, they achieve
 *  maximum performance where data are guaranteed correct by other means.
 *  Use the mutator functions (same name as the macro, but lower case)
 *  for more robust code with a small performance penalty.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

/* temp-gff-region-mutators.c */
int bl_gff3_region_set_count(bl_gff3_region_t *bl_gff3_region_ptr, size_t new_count);
int bl_gff3_region_set_goi_index(bl_gff3_region_t *bl_gff3_region_ptr, size_t new_goi_index);
int bl_gff3_region_set_species(bl_gff3_region_t *bl_gff3_region_ptr, char *new_species);
int bl_gff3_region_set_species_ae(bl_gff3_region_t *bl_gff3_region_ptr, size_t c, char new_species_element);
int bl_gff3_region_set_species_cpy(bl_gff3_region_t *bl_gff3_region_ptr, char *new_species, size_t array_size);
int bl_gff3_region_set_goi(bl_gff3_region_t *bl_gff3_region_ptr, char *new_goi);
int bl_gff3_region_set_goi_ae(bl_gff3_region_t *bl_gff3_region_ptr, size_t c, char new_goi_element);
int bl_gff3_region_set_goi_cpy(bl_gff3_region_t *bl_gff3_region_ptr, char *new_goi, size_t array_size);
