    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the bl_gff_region_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define BL_GFF_REGION_COUNT(ptr)        ((ptr)->count)
#define BL_GFF_REGION_GOI_INDEX(ptr)    ((ptr)->goi_index)
#define BL_GFF_REGION_FEATURES(ptr)     ((ptr)->features)
#define BL_GFF_REGION_FEATURES_AE(ptr,c) ((ptr)->features[c])
#define BL_GFF_REGION_SPECIES(ptr)      ((ptr)->species)
#define BL_GFF_REGION_SPECIES_AE(ptr,c) ((ptr)->species[c])
#define BL_GFF_REGION_GOI(ptr)          ((ptr)->goi)
#define BL_GFF_REGION_GOI_AE(ptr,c)     ((ptr)->goi[c])
#define BL_GFF_REGION_CHROM(ptr)        ((ptr)->chrom)

