#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

release_file=$HOME/.ms-genome-release
if [ ! -e $release_file ]; then
    while [ -z "$release" ]; do
	printf "Genome release? (e.g. 106) "
	read release
    done
    echo $release > $release_file
    printf "Edit $release_file to change.\n"
    pause
fi
release=$(cat $release_file)

curl_flags='--continue-at - --remote-name'
site="http://ftp.ensembl.org/pub/release-$release/fasta"

# No combined primary_assembly files for many species, so we would
# have to download all chromosomes individually and concatenate.
# Remove non-chromosomal sequences from toplevel to get primary_assembly.
for cdna in \
    homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa \
    mus_musculus/cdna/Mus_musculus.GRCm39.cdna.all.fa \
    rattus_norvegicus/cdna/Rattus_norvegicus.mRatBN7.2.cdna.all.fa \
    danio_rerio/cdna/Danio_rerio.GRCz11.cdna.all.fa \
    takifugu_rubripes/cdna/Takifugu_rubripes.fTakRub1.2.cdna.all.fa \
    oryzias_latipes/cdna/Oryzias_latipes.ASM223467v1.cdna.all.fa
do
    base=$(basename $cdna)
    printf "===\n"
    printf "Downloading $base.gz\n"
    url=$site/$cdna.gz
    curl $curl_flags $url
done
