#!/bin/sh

##########################################################################
#   Description:
#       
#   History:
#   Date        Name        Modification
#   2022-03-01  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 GFF-file gene-name [gene-name ...]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 2 ]; then
    usage
fi
file=$1
shift

printf "\n$file:\n"
for gene in "$@"; do
    printf "  $gene:\n"
    awk -v gene=$gene '$3 == "gene" {
	split($9, a, ";");
	for (f in a) {
	    str = "Name=" gene;
	    #print a[f];
	    if ( tolower(a[f]) ~ tolower(str) ) {
		printf("    %2s %6.1fM %s\n", $1, $4 / 1000000, a[f]);
		break;
	    }
	}
    }' $file
done
