#!/bin/sh

##########################################################################
#   Description:
#       Simple menu system for running microsynteny tools
#
#   Conventions:
#       Global variables capitalized, local all lower-case
#       Constants all caps
#
#   History:
#   Date        Name        Modification
#   2022-04-12  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Function description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2022-04-19  Jason Bacon Begin
##########################################################################

extracted_genes()
{
    local genes=$(ls Regions | cut -d - -f 2 | sort -u | tr '\n' ' ')
    printf "Extracted genes:\n\n$genes\n\n"
    return 0
}


##########################################################################
#   Function description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2022-04-19  Jason Bacon Begin
##########################################################################

available_genes()
{
    if [ $# != 1 ]; then
	printf "Usage: available_genes gene-list-filename\n"
	exit 1
    fi
    printf "Available genes:\n\n$(cut -d '|' -f 1 $1 | tr '\n' ' ')\n\n"
    return 0
}


##########################################################################
#   Function description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2022-04-16  Jason Bacon Begin
##########################################################################

get_adjacent_genes_max_nt()
{
    printf "Adjacent genes? [default = 4] "
    read Adjacent_genes
    if [ 0"$Adjacent_genes" = 0 ]; then
	Adjacent_genes=4
    fi
    printf "Max distance in NT? [default = 1,000,000] "
    read Max_nt
    if [ 0"$Max_nt" = 0 ]; then
	Max_nt=1000000
    fi
}


##########################################################################
#   Function description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2022-04-16  Jason Bacon Begin
##########################################################################

get_gene_list_filename()
{
    printf '\nAvailable gene lists (copy and paste one filename):\n\n'
    cd Genes
    ls *-ortho.txt
    cd ..
    local default=de-tf-refined-ortho.txt
    printf "\nGene list? [default = $default] "
    read Gene_list_filename
    if [ 0"$Gene_list_filename" = 0 ]; then
	Gene_list_filename=$default
    fi
    Gene_list_filename="Genes/$Gene_list_filename"
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

if [ ! -d Genes ]; then
    mkdir Genes
    cp %%PREFIX%%/share/microsynteny-tools/Genes/*-ortho.txt Genes
fi

if [ -z "$AWK_PATH" ]; then
    if [ $0 = Scripts/ms-menu ]; then
	# Development: Running from repo dir
	export PATH=$(pwd):$(pwd)/Scripts:$PATH
	export AWK_PATH=$(pwd)/Libexec
	make
    elif [ $0 = ./ms-menu ]; then
	# Development: Running from repo dir
	cd ..
	export PATH=$(pwd):$(pwd)/Scripts:$PATH
	export AWK_PATH=$(pwd)/Libexec
	make
    else
	# Installed
	export AWK_PATH=%%PREFIX%%/libexec
    fi
fi

selection=''
while [ 0"$selection" != 0q ]; do
    clear
    # Benner generated at https://www.ascii-art-generator.org
    cat << EOM
	   __  ____                                  __                   
	  /  |/  (_)_____________  _______  ______  / /____  ____  __  __
	 / /|_/ / / ___/ ___/ __ \/ ___/ / / / __ \/ __/ _ \/ __ \/ / / /
	/ /  / / / /__/ /  / /_/ (__  ) /_/ / / / / /_/  __/ / / / /_/ /
       /_/  /_/_/\___/_/   \____/____/\__, /_/ /_/\__/\___/_/ /_/\__, /
				     /____/                     /____/
			     ______            __
			    /_  __/___  ____  / /____
			     / / / __ \/ __ \/ / ___/
			    / / / /_/ / /_/ / (__  )
			   /_/  \____/\____/_/____/

1.. Download Ensembl GFFs, transcriptomes and genomes (may take a while)
2.. Extract regions
3.. Find intersections between regions across fish and mammals
4.. View stacked regions across species (scale discarded)
5.. Visualize regions in scale
6.. Show percent changed stats for fish and mammals
    (Extract regions for de-tf-ortho.txt and non-de-tf-ortho.txt first)
7.. Locate genes in one or more GFF files
8.. Build/download BLAST databases
9.. BLAST a Danio gene against another species
Q.. Quit

EOM
    printf "Selection? "
    read selection
    case "$selection" in
    1)
	cd GFF
	ms-fetch-gffs
	cd ../Transcriptome
	ms-fetch-cdnas
	cd ../Reference
	ms-fetch-refs
	cd ..
	;;
    
    2)
	get_adjacent_genes_max_nt
	get_gene_list_filename
	mkdir -p Output
	outfile=Output/$(basename ${Gene_list_filename%.txt}-$Adjacent_genes-$Max_nt-extract.out)
	ms-gene-list-extract \
	    --adjacent-genes $Adjacent_genes --max-nt-distance $Max_nt \
	    $Gene_list_filename > $outfile
	printf "\nSummary output saved in $outfile.\n"
	printf "Region GFFs stored in Regions directory.\n"
	pause
	more $outfile
	;;
    
    3)
	get_adjacent_genes_max_nt
	get_gene_list_filename
	mkdir -p Output
	outfile=Output/$(basename ${Gene_list_filename%.txt}-intersect.out)
	ms-gene-list-fish-mammal-intersect \
	    $Adjacent_genes $Max_nt $Gene_list_filename \
	    > $outfile
	printf "\nSummary output saved in $outfile.\n"
	printf "Intersection files stored in Intersects-* directories.\n"
	pause
	more $outfile
	;;
    
    4)
	get_gene_list_filename
	available_genes $Gene_list_filename
	printf "Gene name (case-sensitive)? "
	read gene
	if [ 0"$gene" != 0 ]; then
	    printf '\nAvailable gene regions:\n\n'
	    ls Regions/*-$gene-*.gff3
	    cat << EOM

The last two numbers in each filename above indicate the number of adjacent
genes and maximum distance in NT for that region.  Choose from among these to
answer the next two questions.  You can also generate additional region
files by going back to option 2.

EOM
	    get_adjacent_genes_max_nt
	    ms-stack $Adjacent_genes $Max_nt $Gene_list_filename $gene
	fi
	;;
    
    5)
	get_gene_list_filename
	available_genes $Gene_list_filename
	printf "Gene name (case-sensitive)? "
	read gene
	if [ 0"$gene" != 0 ]; then
	    printf '\nAvailable gene regions:\n\n'
	    ls Regions/*-$gene-*.gff3
	    cat << EOM

The last two numbers in each filename above indicate the number of adjacent
genes and maximum distance in NT for that region.  Choose from among these to
answer the next two questions.  You can also generate additional region
files by going back to option 2.

EOM
	    get_adjacent_genes_max_nt
	    cd Regions
	    printf "\nCopy and paste species names separated by space.\n\n"
	    ls | cut -d - -f 1 | sort | uniq
	    cd ..
	    printf "\nSpecies? [default = all] "
	    read species
	    ms-plot $Adjacent_genes $Max_nt $gene $species
	fi
	;;

    6)
	get_adjacent_genes_max_nt
	ms-fish-mammal-percent-changed $Adjacent_genes $Max_nt
	;;

    7)
	printf "\nHint: Use a portion of a gene name to allow orthologs, e.g. sox11 vs sox11a\n\n"
	printf "Gene names (separated by space)? "
	read gene_list
	if [ -n "$gene_list" ]; then
	    printf "\nAvailable species:\n\n"
	    cd GFF
	    ls *.gff3 | cut -d . -f 1
	    cd ..
	    default_species="Danio_rerio Homo_sapiens Mus_musculus Rattus_norvegicus"
	    printf "\nSpecies? [default = $default_species] "
	    read species_list
	    if [ 0"$species_list" = 0 ]; then
		species_list="$default_species"
	    fi
	    for species in $species_list; do
		gff="GFF/$species.*.gff3"
		ms-locate-gene $gff $gene_list
	    done
	fi
	;;
    
    8)
	ms-blast-dbs
	;;
    
    9)
	ms-blast
	;;
    
    Q|q)
	exit 0
	;;
	
    *)
	printf "Invalid selection: $selection\n"
	;;
    esac
    pause
done
